-- MPT-1003: key-based i18n table for bot responses (seed files live in /locales).
-- Applied to project xmdmkumwxpgahmlweuug (MyPrivacyTOOL Project2) on 2026-10-07.
-- service_role only, like the other non-user-facing tables: RLS on, anon/authenticated grants revoked.
-- Rollback: drop table public.localization;
create table public.localization (
  id          bigint generated by default as identity primary key,
  key         text not null,                      -- e.g. 'bot.confirmed_y.title'
  locale      text not null,                      -- e.g. 'en', 'ja', 'zh'
  value       text not null,                      -- translated string
  description text,                               -- context for translators/AI
  status      text default 'draft',               -- 'draft' | 'review' | 'approved'
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);
create unique index idx_localization_key_locale on public.localization (key, locale);
alter table public.localization enable row level security;
revoke all on public.localization from anon, authenticated;
create policy "Enable all access for service role" on public.localization
  for all using (auth.role() = 'service_role');
