// Generates lib/guides.generated.js from src/data/optOutGuides.json.
// Why: wrangler's bundler cannot parse `import ... with { type: 'json' }` and Node 22 (tests) requires it
// for a plain JSON import, so the Worker imports a generated JS module instead. CI runs this before
// test + deploy so the module can never go stale relative to the JSON.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const src = fileURLToPath(new URL('../../../src/data/optOutGuides.json', import.meta.url));
const out = fileURLToPath(new URL('../lib/guides.generated.js', import.meta.url));
const guides = JSON.parse(readFileSync(src, 'utf8'));
writeFileSync(
  out,
  `// GENERATED by scripts/sync-guides.mjs from src/data/optOutGuides.json - do not edit by hand.\nexport default ${JSON.stringify(guides, null, 2)};\n`,
);
console.log(`guides.generated.js: ${guides.length} guides`);
